"""initial_schema

Revision ID: d43ca997481e
Revises: 
Create Date: 2026-07-19 19:52:20.012614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43ca997481e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias_maquina', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_categorias_maquina_nombre'), 'categorias_maquina', ['nombre'], unique=True)
    op.alter_column('clientes', 'cedula',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'fecha_registro',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('clientes', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clientes', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('clientes_cedula_key'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cedula'), 'clientes', ['cedula'], unique=True)
    op.create_index(op.f('ix_clientes_usuario_id'), 'clientes', ['usuario_id'], unique=True)
    op.alter_column('control_accesos', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('control_accesos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('control_accesos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_control_accesos_cliente_id'), 'control_accesos', ['cliente_id'], unique=False)
    op.alter_column('detalles_venta', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalles_venta', 'venta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalles_venta', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalles_venta', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_detalles_venta_producto_id'), 'detalles_venta', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_venta_id'), 'detalles_venta', ['venta_id'], unique=False)
    op.drop_column('detalles_venta', 'precio_unitario')
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disciplinas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_disciplinas_nombre'), 'disciplinas', ['nombre'], unique=True)
    op.alter_column('entrenadores', 'especialidad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entrenadores', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entrenadores', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_entrenadores_usuario_id'), 'entrenadores', ['usuario_id'], unique=True)
    op.alter_column('evaluaciones_biometricas', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('evaluaciones_biometricas', 'peso',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('evaluaciones_biometricas', 'estatura',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('evaluaciones_biometricas', 'porcentaje_grasa',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('evaluaciones_biometricas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evaluaciones_biometricas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_evaluaciones_biometricas_cliente_id'), 'evaluaciones_biometricas', ['cliente_id'], unique=False)
    op.alter_column('maquinas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maquinas', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('maquinas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_maquinas_categoria_id'), 'maquinas', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_maquinas_nombre'), 'maquinas', ['nombre'], unique=False)
    op.alter_column('membresias_cliente', 'fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('membresias_cliente', 'fecha_vencimiento',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('membresias_cliente', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('membresias_cliente', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('membresias_cliente', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_membresias_cliente_cliente_id'), 'membresias_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_membresias_cliente_plan_id'), 'membresias_cliente', ['plan_id'], unique=False)
    op.alter_column('pagos', 'monto',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('pagos', 'fecha_pago',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pagos', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pagos', 'membresia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pagos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pagos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_pagos_membresia_id'), 'pagos', ['membresia_id'], unique=False)
    op.create_index(op.f('ix_pagos_usuario_id'), 'pagos', ['usuario_id'], unique=False)
    op.alter_column('planes_suscripcion', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('planes_suscripcion', 'precio',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('planes_suscripcion', 'duracion_dias',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planes_suscripcion', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_planes_suscripcion_nombre'), 'planes_suscripcion', ['nombre'], unique=True)
    op.alter_column('productos_tienda', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('productos_tienda', 'precio',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('productos_tienda', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productos_tienda', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reservas', 'fecha_reserva',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservas', 'sesion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_reservas_sesion_id'), 'reservas', ['sesion_id'], unique=False)
    op.alter_column('roles', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('roles_nombre_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.alter_column('sesiones_programadas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'hora_inicio',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'hora_fin',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'cupo_maximo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'disciplina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'entrenador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sesiones_programadas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sesiones_programadas_disciplina_id'), 'sesiones_programadas', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_sesiones_programadas_entrenador_id'), 'sesiones_programadas', ['entrenador_id'], unique=False)
    op.alter_column('tickets_mantenimiento', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets_mantenimiento', 'fecha_apertura',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tickets_mantenimiento', 'maquina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets_mantenimiento', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets_mantenimiento', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_tickets_mantenimiento_maquina_id'), 'tickets_mantenimiento', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_tickets_mantenimiento_usuario_id'), 'tickets_mantenimiento', ['usuario_id'], unique=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False)
    op.alter_column('ventas_tienda', 'fecha_venta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ventas_tienda', 'total',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ventas_tienda', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ventas_tienda', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_ventas_tienda_cliente_id'), 'ventas_tienda', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_tienda_cliente_id'), table_name='ventas_tienda')
    op.alter_column('ventas_tienda', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ventas_tienda', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ventas_tienda', 'total',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('ventas_tienda', 'fecha_venta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_tickets_mantenimiento_usuario_id'), table_name='tickets_mantenimiento')
    op.drop_index(op.f('ix_tickets_mantenimiento_maquina_id'), table_name='tickets_mantenimiento')
    op.alter_column('tickets_mantenimiento', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets_mantenimiento', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets_mantenimiento', 'maquina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets_mantenimiento', 'fecha_apertura',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tickets_mantenimiento', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_sesiones_programadas_entrenador_id'), table_name='sesiones_programadas')
    op.drop_index(op.f('ix_sesiones_programadas_disciplina_id'), table_name='sesiones_programadas')
    op.alter_column('sesiones_programadas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'entrenador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'disciplina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'cupo_maximo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'hora_fin',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'hora_inicio',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sesiones_programadas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.create_unique_constraint(op.f('roles_nombre_key'), 'roles', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_reservas_sesion_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.alter_column('reservas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reservas', 'sesion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reservas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reservas', 'fecha_reserva',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('productos_tienda', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('productos_tienda', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productos_tienda', 'precio',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('productos_tienda', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_planes_suscripcion_nombre'), table_name='planes_suscripcion')
    op.alter_column('planes_suscripcion', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planes_suscripcion', 'duracion_dias',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planes_suscripcion', 'precio',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('planes_suscripcion', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pagos_usuario_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_membresia_id'), table_name='pagos')
    op.alter_column('pagos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pagos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pagos', 'membresia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pagos', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pagos', 'fecha_pago',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pagos', 'monto',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_index(op.f('ix_membresias_cliente_plan_id'), table_name='membresias_cliente')
    op.drop_index(op.f('ix_membresias_cliente_cliente_id'), table_name='membresias_cliente')
    op.alter_column('membresias_cliente', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('membresias_cliente', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('membresias_cliente', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('membresias_cliente', 'fecha_vencimiento',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('membresias_cliente', 'fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_maquinas_nombre'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_categoria_id'), table_name='maquinas')
    op.alter_column('maquinas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maquinas', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('maquinas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_evaluaciones_biometricas_cliente_id'), table_name='evaluaciones_biometricas')
    op.alter_column('evaluaciones_biometricas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('evaluaciones_biometricas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evaluaciones_biometricas', 'porcentaje_grasa',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('evaluaciones_biometricas', 'estatura',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('evaluaciones_biometricas', 'peso',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('evaluaciones_biometricas', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_entrenadores_usuario_id'), table_name='entrenadores')
    op.alter_column('entrenadores', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entrenadores', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entrenadores', 'especialidad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_disciplinas_nombre'), table_name='disciplinas')
    op.alter_column('disciplinas', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('detalles_venta', sa.Column('precio_unitario', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_detalles_venta_venta_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_producto_id'), table_name='detalles_venta')
    op.alter_column('detalles_venta', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalles_venta', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalles_venta', 'venta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalles_venta', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_control_accesos_cliente_id'), table_name='control_accesos')
    op.alter_column('control_accesos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('control_accesos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('control_accesos', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_clientes_usuario_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cedula'), table_name='clientes')
    op.create_unique_constraint(op.f('clientes_cedula_key'), 'clientes', ['cedula'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clientes', 'fecha_registro',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('clientes', 'cedula',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_categorias_maquina_nombre'), table_name='categorias_maquina')
    op.alter_column('categorias_maquina', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
